name: Build Native

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 8 * * 2'
  #push:
    # tags:
    #   - "v*"

env:
  PROJECT_DIR: NeuralAmpModeler
  ARTIFACT_NAME: NAM On Steroids Beta 3B

jobs:
  build:
    name: Build-native-plugins
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, windows-2022, ubuntu-latest]
        include:
          - os: macos-15
            build_dir: build-mac
            artifact_ext: mac
          - os: windows-2022
            build_dir: build-win
            artifact_ext: win
          - os: ubuntu-latest
            build_dir: build-linux
            artifact_ext: linux

    steps:
    - name: Check out repository
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Prepare Beta 3B sources
      run: bash .github/scripts/prepare_beta3b.sh
      shell: bash

    - name: Get VST3 SDK
      run: |
        cd iPlug2/Dependencies/IPlug
        ./download-iplug-sdks.sh
      shell: bash

    - name: Get Prebuilt Libs
      run: |
        cd iPlug2/Dependencies
        ./download-prebuilt-libs.sh
      shell: bash

    - name: Build macOS
      if: matrix.os == 'macos-15'
      run: |
        cd ${{env.PROJECT_DIR}}/scripts
        ./makedist-mac.sh full zip
      shell: bash

    - name: Build Linux VST3
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd ${{env.PROJECT_DIR}}/scripts
        bash ./makedist-linux.sh
      shell: bash

    - name: Add msbuild to PATH (Windows)
      if: matrix.os == 'windows-2022'
      uses: microsoft/setup-msbuild@v3

    - name: Build Windows
      if: matrix.os == 'windows-2022'
      run: |
        cd ${{env.PROJECT_DIR}}\scripts
        .\makedist-win.bat full zip
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{env.ARTIFACT_NAME}}-${{matrix.artifact_ext}}
        path: ${{env.PROJECT_DIR}}/${{matrix.build_dir}}/out
